module.exports = {
  pingTimeout: 5000,
  nodeInfoURL: 'http://testnet-master.blockstack.org:20443/v2/info',
  neonNodeInfoURL: 'http://neon.blockstack.org/v2/info',
  sidecarURL: 'https://stacks-node-api.blockstack.org/extended',
  sidecarURLKrypton: 'https://stacks-node-api.krypton.blockstack.org/extended',
  sidecarTxURL: 'https://stacks-node-api.blockstack.org/extended/v1/tx',
  explorerURL: 'https://testnet-explorer.blockstack.org',
  faucetURL: 'https://stacks-node-api.blockstack.org/extended/v1/faucets/stx?address=',
  nodeStatusURL: 'https://status.test-blockstack.com',
  binanceAPIURL: 'https://api.binance.com/api/v3',
  masterNodeKey: 'master_node_ping',
  stackNodeAPIURL: 'http://localhost:5000',
  sidecarKey: 'sidecar_ping',
  explorerKey: 'explorer_ping',
  stacksChainTipKey: 'stacks_chain_tip',
  lastStacksChainTipHeightKey: 'last_stacks_chain_tip_height',
  lastStacksChainTipHeightTimeKey: 'last_stacks_chain_tip_height_time',
  lastBurnBlockHeightKey: 'last_burn_block_height',
  lastBurnBlockHeightTimeKey: 'last_burn_block_height_time',
  lastChainResetKey: 'last_chain_reset',
  exitAtBlockKey: 'exit_at_block',
  reseedingStepKey: 'reseeding_step',
  reseedNextBlockKey: 'reseed_next_block',
  reseedTryCountKey: 'reseed_try_count',
  reseedMaxTryCount: 5,
  reseedAbortErrorKey: 'reseed_abort_error_key',
  reseedRandomKey: 'reseed_random_key',
  reseedRandomAddress: 'reseed_random_address',
  ReseedingSteps: {
    NotReseeding: 0,
    Setup: 1,
    TokenTransfer: 2,
    ContractDeploy: 3,
    ContractCall: 4,
  },
  reseedStepMinBlocks: 2,
  seededFaucetTxKey: 'seeded_faucet_tx',
  seededTokenTransferTxKey: 'seeded_token_transfer_tx',
  seededContractDeployTxKey: 'seeded_contract_deploy_tx',
  seededContractCallTxKey: 'seeded_contract_call_tx',
  seededFaucetTxStatusKey: 'seeded_faucet_tx_status',
  seededTokenTransferTxStatusKey: 'seeded_token_transfer_tx_status',
  seededContractDeployTxStatusKey: 'seeded_contract_deploy_tx_status',
  seededContractCallTxStatusKey: 'seeded_contract_call_tx_status',
  seededFaucetTxBroadcastTimeKey: 'seeded_faucet_tx_broadcast_time',
  seededTokenTransferTxBroadcastTimeKey: 'seeded_token_transfer_tx_broadcast_time',
  seededContractDeployTxBroadcastTimeKey: 'seeded_contract_deploy_tx_broadcast_time',
  seededContractCallTxBroadcastTimeKey: 'seeded_contract_call_tx_broadcast_time',
  historicalDataMax: 72,
  blockRateYellowCount: 18,
  blockRateRedCount: 5,
  burnChainBlockRate: 30,
  MIN_MINER_BTC_AMOUNT: 0.005,

  // language
  CN: 'zh-CN',

  // password key
  MiningPasswordAuthorization: 'MiningPasswordAuthorization',
  // password value
  MiningPassword: 'MiningPassword',
  // sha algorithm
  sha256: 'sha256',
  sha512: 'sha512',
  shaSecret: 'MiningBot-Client@2020',
  hexToken: 'hex',
  // aes algorithm
  aes256Gcm: 'aes-256-gcm',
  aesKeySize: 32,
  // address type
  btcType: 1,
  stxType: 2,
}
